### ISSUE TITLE
Stopped working on NeoVim 0.4.4

### ISSUE THREAD

**Issue by oblitum** [atchim/underworld.vim#2]
Hi. I used to use this plugin but lately when starting it I get errors on NeoVim 0.4.4. I'm not running NeoVim nightlies, so, can't use "0.5" yet.

**Comment by atchim** [comment]
Thank you for reporting this issue. I didn't realize that Neovim 0.4 doesn't support function arguments with defualt values, which is similar to optional arguments in Python. It should work fine for you now.

**Comment by oblitum** [comment]
Thanks. Notice a fix is also needed in the lightline code.

**Comment by atchim** [comment]
Fixed. Sorry, I forgot to check the color scheme file for lightline.vim.
